apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 115287631585.dkr.ecr.us-east-1.amazonaws.com/clo835-ass1:my_db_v1
    imagePullPolicy: Always
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
  imagePullSecrets:
  - name: ecr-secret
