apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: mysql-ns
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPO_NAME>:my_db_v1
    imagePullPolicy: Always
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "<REPLACE_WITH_YOUR_PASSWORD>"