apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs
  namespace: web-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: web
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/<ECR_REPO_NAME>:my_app_v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-service.mysql-ns.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "<REPLACE_WITH_YOUR_PASSWORD>"
        - name: DATABASE
          value: "employees"
        - name: APP_COLOR
          value: "blue"